@startuml DashboardServiceSequence

actor "Fleet Management Team" as FleetTeam
participant "Dashboard" as Dashboard
participant "DashboardService" as DashboardService
participant "BookingCenter" as BookingCenter
participant "TaxiFleet" as TaxiFleet
participant "PersistenceService" as PersistenceService


FleetTeam -> Dashboard : renderInitialDashboard()
Dashboard -> DashboardService : generateBookingStats()
DashboardService -> BookingCenter : queryBooking()
BookingCenter -> PersistenceService : getAllBookings()
PersistenceService -> BookingCenter : Collection<Booking>
BookingCenter -> DashboardService : Collection<Booking>
DashboardService -> Dashboard : displayBookingStats(Collection<Booking>)

Dashboard -> DashboardService : generateTaxiStats()
DashboardService -> TaxiFleet : queryTaxis()
TaxiFleet -> PersistenceService : getAllTaxis()
PersistenceService -> TaxiFleet : Collection<Taxi>
TaxiFleet -> DashboardService : Collection<Taxi>
DashboardService -> Dashboard : displayTaxiStats(Collection<Taxi>)