@startuml useCases
actor "Booking Center" as BookingCenter
actor "Taxi" as Taxi

rectangle "Fleet Management Module" {
  BookingCenter --> (List All Taxis) 
  BookingCenter --> (Publish New Booking) 
  BookingCenter --> (View Dashboard)
}

rectangle "Taxi Module" {
  Taxi --> (Accept Booking) 
  Taxi --> (Update Status)
}

@enduml
