version: '3.8'

services:

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: taxiFleet
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./Sources/com.pal.taxi.management
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build:
      context: ./Sources/taxi-fleet-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  pgdata:
